version: '3.8'

services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    ports:
      - '5432:5432'

  app:
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./app:/opt/build/app
      - ./config:/opt/build/config
      - ./db:/opt/build/db
    environment:
      NODE_ENV: development
      PG_HOST: postgres
    depends_on:
      - postgres
    entrypoint: ["npm", "run", "start:dev"]
